# Generated by Django 6.0 on 2025-12-28 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=25)),
                ('value', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
                'db_table': 'option_table',
                'unique_together': {('field_name', 'value')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.CharField(max_length=11, unique=True)),
                ('product_code_other', models.CharField(db_index=True, max_length=25, unique=True)),
                ('variant_name', models.TextField()),
                ('template_name', models.TextField()),
                ('list_price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('wholesale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('manual', models.CharField(max_length=5)),
                ('prebook', models.BooleanField(default=False)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('custom_description', models.TextField()),
                ('buyer_sku', models.CharField(max_length=10)),
                ('nu_customer_group', models.CharField(max_length=10)),
                ('country_of_origin', models.CharField(max_length=10)),
                ('age_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='age_range_product', to='Coltheler.option')),
                ('cost_price_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_price_method_product', to='Coltheler.option')),
                ('dimension_uom_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dimension_uom_name_product', to='Coltheler.option')),
                ('hs_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hs_code_products', to='Coltheler.option')),
                ('lifecycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_product', to='Coltheler.option')),
                ('price_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_method_product', to='Coltheler.option')),
                ('style_ranking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='style_ranking_product', to='Coltheler.option')),
                ('supplier_name', models.ManyToManyField(related_name='supplier_name_product', to='Coltheler.option')),
                ('tax_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_code_product', to='Coltheler.option')),
                ('weight_uom_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weight_uom_name_product', to='Coltheler.option')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic')),
                ('address', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
