# Generated by Django 6.0 on 2026-01-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Coltheler", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="product",
            name="uniq_product_upc_product_code_other",
        ),
        migrations.AlterField(
            model_name="product",
            name="product_code_other",
            field=models.CharField(db_index=True, max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="upc",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
