# Generated by Django 6.0 on 2026-01-31 08:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Coltheler",
            "0002_remove_product_uniq_product_upc_product_code_other_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Gs1UploadTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "gs1_company_prefix",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                (
                    "packaging_level",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("desc_1_language", models.CharField(default="en", max_length=5)),
                ("brand_name", models.CharField(blank=True, max_length=50, null=True)),
                ("brand_1_language", models.CharField(default="en", max_length=5)),
                ("is_variable", models.BooleanField(default=False)),
                ("is_purchasable", models.BooleanField(default=False)),
                (
                    "sku",
                    models.CharField(
                        blank=True, db_index=True, max_length=25, null=True, unique=True
                    ),
                ),
                (
                    "global_product_classification",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "gs1_upload_template_table",
            },
        ),
        migrations.AddField(
            model_name="option",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="option",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="MasterUpc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upc", models.CharField(max_length=15, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="upcs",
                        to="Coltheler.gs1uploadtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "master_upc",
            },
        ),
        migrations.AddField(
            model_name="gs1uploadtemplate",
            name="gtin",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gs1_product",
                to="Coltheler.masterupc",
            ),
        ),
        migrations.CreateModel(
            name="PoTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=50, unique=True)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("variant_name", models.TextField(blank=True, null=True)),
                (
                    "sku",
                    models.CharField(
                        blank=True, db_index=True, max_length=25, null=True
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("warehouse", models.CharField(blank=True, max_length=50, null=True)),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("reference_have_whl", models.BooleanField(default=False)),
                ("requested_shipping_date", models.DateField(blank=True, null=True)),
                ("sample_po", models.BooleanField(default=False)),
                ("gs1_indicator", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "style_ranking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="style_ranking_po",
                        to="Coltheler.option",
                    ),
                ),
            ],
            options={
                "db_table": "po_template_table",
            },
        ),
        migrations.AddConstraint(
            model_name="gs1uploadtemplate",
            constraint=models.UniqueConstraint(
                fields=("sku", "gtin"), name="unique_sku_gtin"
            ),
        ),
    ]
