# Generated by Django 6.0 on 2026-02-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Coltheler", "0003_gs1uploadtemplate_option_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="potemplate",
            name="reference",
            field=models.CharField(max_length=50),
        ),
    ]
