# Generated by Django 6.0 on 2026-02-15 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Coltheler", "0005_asset"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="asset",
            new_name="asset_file_uploade_9accde_idx",
            old_name="asset_file_uploade_4fec67_idx",
        ),
        migrations.RenameIndex(
            model_name="asset",
            new_name="asset_file_relativ_60f260_idx",
            old_name="asset_file_relativ_8f3f39_idx",
        ),
    ]
